version: "3.0"

services:
  app1:
    build: ./baseapp
    image: aktercloudpro/flask:app
    ports:
      - "5001:5000"

  app2:
    image: aktercloudpro/flask:app
    ports:
      - "5002:5000"

  app3:
    image: aktercloudpro/flask:app
    ports:
      - "5003:5000"
  
  nginx:
    build: ./nginx
    image: aktercloudpro/nginx:loadbalancer
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
      - app3
